### ISSUE TITLE
Upgrade to libdeflate 1.18

### ISSUE THREAD

**Issue by ebiggers** [benkasminbullock/gzip-libdeflate#6]
Please stay up to date with the latest version of libdeflate so that people don't run into issues that have already been fixed. Thanks!

**Comment by benkasminbullock** [comment]
Do you have an announcement or something I should subscribe to?

**Comment by ebiggers** [comment]
You can make GitHub notify you about new releases.  At https://github.com/ebiggers/libdeflate click Watch, then Custom, then Releases, then Apply.

**Comment by benkasminbullock** [comment]
The underlying library is updated to 1.18 in the latest CPAN release 0.05. I've also subscribed to the releases channel for the library.
