### ISSUE TITLE
GCC version mismatch on some third-party distributions.

### ISSUE THREAD

**Issue by hbasrc** [benkasminbullock/gzip-libdeflate#7]
> Makefile.PL
Your C compiler, gcc 1, is too old for libdeflate, the minimum requirement is version 4.9 at inc/CheckCCVersion.
pm line 43.

> gcc --version
gcc (tdm-1) 5.1.0
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Fix in CheckCCVersion.pm
```
    if ($version =~ /gcc.*?([0-9.]+)$/m) {
	compiler ('gcc', $1, $gccmin);
	return;
    }

```

**Comment by benkasminbullock** [comment]
I've uploaded version 0.08_01 with a slightly improved check. Can you let me know if it works?

**Comment by hbasrc** [comment]
It works fine now.

However, if there are version characters in the middle, it will still fail, although I am not sure whether there is such a special case.
such as:
> gcc (xxxx-1.1) 5.1.0
> Copyright (C) 2015 Free Software Foundation, Inc.

Maybe using `clang/gcc -dumpversion` to get the version number is more reliable.

```
sub check_cc_version
{
    my $cc = $Config{cc};
    if (! $cc) {
	die "I cannot find a C compiler in your \%Config";
    }
    my ($version) = `$cc -dumpversion` =~ /($vre)/;
    if ($cc =~ /clang/i) {
	compiler ('clang', $version, $clangmin);
	return;
    }
    if ($cc =~ /gcc/i) {
	compiler ('gcc', $version, $gccmin);
	return;
    }
    # Need to add tests for MSVC compiler here to check it is 2015 or
    # later, according to Biggers' README page.
}
```

**Comment by benkasminbullock** [comment]
I don't have a reliable way to get the version of the compiler other than by this sort of method. If there is one, hopefully we can rewrite this to improve it.
